version: '3'
services:
  myapp:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./user_ids.txt:/app/user_ids.txt
    restart: always
    environment:
      - openAI_API_KEY=${openAI_API_KEY}
      - bot_API_KEY=${bot_API_KEY}
