version: '3'
services:
  myapp:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./user_TheHackerNews.txt:/app/user_TheHackerNews.txt
      - ./user_TechNews.txt:/app/user_TechNews.txt
      - ./user_VentureBeat.txt:/app/user_VentureBeat.txt
      # - /etc/localtime:/etc/localtime:ro
    restart: always
    environment:
      - openAI_API_KEY=${openAI_API_KEY}
      - bot_API_KEY=${bot_API_KEY}
      - TZ=Asia/Taipei
